SELECT * FROM employee;

INSERT INTO employee (name, age, department, gender, salary)
VALUES ('VISHAL SINGH', 22, 'COMPUTER APPLICATION', 'MALE', 25000),
('AVNISH KAUSHIK', 22, 'COMPUTER SCIENCE', 'MALE', 25000),
('PRIYA SHARMA', 21, 'INFORMATION TECHNOLOGY', 'FEMALE', 24000),
('RAHUL VERMA', 23, 'COMPUTER SCIENCE', 'MALE', 26000),
('ANKITA JAIN', 22, 'COMPUTER APPLICATION', 'FEMALE', 25500),
('SUMIT KUMAR', 24, 'INFORMATION TECHNOLOGY', 'MALE', 24500),
('NEHA SINGH', 21, 'COMPUTER SCIENCE', 'FEMALE', 25000);

